spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: songgang1334@gmail.com
    password: oghxdlcjdlnubnws
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true