spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(MAQBwhpn0DaSYyZyzY3wv/8UTRIpmvwneJKXW7C7hgs=)
    password: ENC(7htD8P8ePu32cJL0D8SZfyzWodoqaKGhzULqHy6ZRxY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator