spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(ywyPJ+QmHkIagnj4eIz7TbUfnWnI6kxbntrdsFqvFCc=)
    password: ENC(HJRQVUZ8SOPelSNoMCE5vO1/7hkiKSD/we1edFBtJbo=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(o1309Z71MOOhCdlgCjmgyNGw9CKuIB1RIzkO0ToqSCJbgOIaxZNfD40POQZks7uU)
            redirect-uri: ENC(CJ9I/fsHptAbjcSHfwpl75LvrkyEca0AJXROIbX8IOB/YwFxXtgfYP37p0oOJ33TiONOJ10yBHCZ8tFqSaFlolnSxy+nU32G)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_PASSWORD}